"""Add oauth_provider,defaul elo

Revision ID: 439ed0b7a313
Revises: 94d8adf331b3
Create Date: 2026-04-28 22:58:05.208503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '439ed0b7a313'
down_revision: Union[str, Sequence[str], None] = '94d8adf331b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rating')
    op.drop_column('users', 'team')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('team', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###