"""Fix models

Revision ID: 94d8adf331b3
Revises: 49bd04695453
Create Date: 2026-04-28 19:36:25.144255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d8adf331b3'
down_revision: Union[str, Sequence[str], None] = '49bd04695453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friendships_id'), table_name='friendships')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_index(op.f('ix_tournaments_id'), table_name='tournaments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_tournaments_id'), 'tournaments', ['id'], unique=False)
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_friendships_id'), 'friendships', ['id'], unique=False)
    # ### end Alembic commands ###
